package one.xis.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.regex.Pattern;

public class GenerateNativeRunnerTask extends DefaultTask {

    private static final Pattern PACKAGE_PATTERN = Pattern.compile("^\\s*package\\s+([a-zA-Z0-9_.]+)\\s*;", Pattern.MULTILINE);
    private static final Pattern CLASS_PATTERN = Pattern.compile("(?:(?:public|final|abstract)\\s+)*class\\s+([A-Za-z_$][A-Za-z0-9_$]*)\\b");

    private final ConfigurableFileCollection sourceFiles = getProject().files();
    private final DirectoryProperty outputDirectory = getProject().getObjects().directoryProperty();

    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public ConfigurableFileCollection getSourceFiles() {
        return sourceFiles;
    }

    @OutputDirectory
    public DirectoryProperty getOutputDirectory() {
        return outputDirectory;
    }

    @TaskAction
    public void generate() throws IOException {
        var outputDir = outputDirectory.get().getAsFile();
        getProject().delete(outputDir);
        var applicationClass = findApplicationClass();
        if (applicationClass == null) {
            return;
        }
        var packageDir = new File(outputDir, "one/xis/boot/nativeimage");
        Files.createDirectories(packageDir.toPath());
        Files.writeString(new File(packageDir, "NativeRunner.java").toPath(), source(applicationClass), StandardCharsets.UTF_8);
    }

    private String findApplicationClass() throws IOException {
        var matches = new ArrayList<String>();
        for (File sourceFile : sourceFiles.getFiles().stream().sorted(Comparator.comparing(File::getPath)).toList()) {
            if (!sourceFile.isFile() || !sourceFile.getName().endsWith(".java")) {
                continue;
            }
            var source = Files.readString(sourceFile.toPath(), StandardCharsets.UTF_8);
            if (!source.contains("@XISBootApplication") && !source.contains("@one.xis.boot.XISBootApplication")) {
                continue;
            }
            var packageMatcher = PACKAGE_PATTERN.matcher(source);
            var classMatcher = CLASS_PATTERN.matcher(source);
            if (packageMatcher.find() && classMatcher.find()) {
                matches.add(packageMatcher.group(1) + "." + classMatcher.group(1));
            }
        }
        if (matches.size() > 1) {
            throw new GradleException("Multiple @XISBootApplication classes found: " + matches);
        }
        return matches.isEmpty() ? null : matches.get(0);
    }

    private static String source(String applicationClass) {
        return """
                package one.xis.boot.nativeimage;

                /**
                 * Generated by Gradle. Do not edit manually.
                 */
                public final class NativeRunner {

                    private NativeRunner() {
                    }

                    public static void main(String[] args) {
                        one.xis.boot.nativeimage.XISNativeBootRunner.run(
                                %s.class,
                                args,
                                new one.xis.generated.XisGeneratedApplicationComponents());
                    }
                }
                """.formatted(applicationClass);
    }
}
