package one.xis.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.regex.Pattern;

public class GenerateNativeRunnerTask extends DefaultTask {

    private static final Pattern PACKAGE_PATTERN = Pattern.compile("^\\s*package\\s+([a-zA-Z0-9_.]+)\\s*;?", Pattern.MULTILINE);
    private static final Pattern CLASS_PATTERN = Pattern.compile("(?:(?:public|final|abstract|data|open|internal)\\s+)*class\\s+([A-Za-z_$][A-Za-z0-9_$]*)\\b");

    private final ConfigurableFileCollection sourceFiles = getProject().files();
    private final DirectoryProperty outputDirectory = getProject().getObjects().directoryProperty();
    private final Property<String> nativeRuntimePackage = getProject().getObjects().property(String.class);
    private final Property<String> applicationAnnotationName = getProject().getObjects().property(String.class);
    private final Property<String> fullyQualifiedApplicationAnnotationName = getProject().getObjects().property(String.class);

    public GenerateNativeRunnerTask() {
        nativeRuntimePackage.convention("one.xis.boot.nativeimage");
        applicationAnnotationName.convention("XISBootApplication");
        fullyQualifiedApplicationAnnotationName.convention("one.xis.boot.XISBootApplication");
    }

    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public ConfigurableFileCollection getSourceFiles() {
        return sourceFiles;
    }

    @OutputDirectory
    public DirectoryProperty getOutputDirectory() {
        return outputDirectory;
    }

    @Input
    public Property<String> getNativeRuntimePackage() {
        return nativeRuntimePackage;
    }

    @Input
    public Property<String> getApplicationAnnotationName() {
        return applicationAnnotationName;
    }

    @Input
    public Property<String> getFullyQualifiedApplicationAnnotationName() {
        return fullyQualifiedApplicationAnnotationName;
    }

    @TaskAction
    public void generate() throws IOException {
        var outputDir = outputDirectory.get().getAsFile();
        getProject().delete(outputDir);
        var applicationClass = findApplicationClass();
        if (applicationClass == null) {
            return;
        }
        var packageDir = new File(outputDir, nativeRuntimePackage.get().replace('.', '/'));
        Files.createDirectories(packageDir.toPath());
        Files.writeString(new File(packageDir, "NativeApp.java").toPath(), source(applicationClass), StandardCharsets.UTF_8);
    }

    private String findApplicationClass() throws IOException {
        var matches = new ArrayList<String>();
        for (File sourceFile : sourceFiles.getFiles().stream().sorted(Comparator.comparing(File::getPath)).toList()) {
            if (!sourceFile.isFile() || !(sourceFile.getName().endsWith(".java") || sourceFile.getName().endsWith(".kt"))) {
                continue;
            }
            var source = Files.readString(sourceFile.toPath(), StandardCharsets.UTF_8);
            if (!source.contains("@" + applicationAnnotationName.get())
                    && !source.contains("@" + fullyQualifiedApplicationAnnotationName.get())) {
                continue;
            }
            var packageMatcher = PACKAGE_PATTERN.matcher(source);
            var classMatcher = CLASS_PATTERN.matcher(source);
            if (packageMatcher.find() && classMatcher.find()) {
                matches.add(packageMatcher.group(1) + "." + classMatcher.group(1));
            }
        }
        if (matches.size() > 1) {
            throw new GradleException("Multiple @" + applicationAnnotationName.get() + " classes found: " + matches);
        }
        return matches.isEmpty() ? null : matches.get(0);
    }

    private String source(String applicationClass) {
        return """
                package %s;

                /**
                 * Generated by Gradle. Do not edit manually.
                 */
                public final class NativeApp {

                    private NativeApp() {
                    }

                    public static void main(String[] args) {
                        %s.%s.run(
                                %s.class,
                                args,
                                new one.xis.generated.XisGeneratedApplicationComponents());
                    }
                }
                """.formatted(nativeRuntimePackage.get(), nativeRuntimePackage.get(), nativeRunnerClassName(),
                applicationClass);
    }

    private String nativeRunnerClassName() {
        return nativeRuntimePackage.get().equals("one.xis.http.nativeimage")
                ? "XISHttpNativeRunner"
                : "XISBootNativeRunner";
    }
}
