package one.xis.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Comparator;
import java.util.Collection;
import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class GenerateBootFrameworkCatalogTask extends DefaultTask {

    private static final Pattern PACKAGE_PATTERN = Pattern.compile("^\\s*package\\s+([a-zA-Z0-9_.]+)\\s*;", Pattern.MULTILINE);
    private static final Pattern CLASS_PATTERN = Pattern.compile("\\bclass\\s+([A-Za-z_$][A-Za-z0-9_$]*)\\b");

    private final ConfigurableFileCollection registrySourceRoots = getProject().files();
    private final DirectoryProperty outputDirectory = getProject().getObjects().directoryProperty();
    private final Property<String> nativeRuntimePackage = getProject().getObjects().property(String.class);
    private final Property<String> generatedClassName = getProject().getObjects().property(String.class);

    public GenerateBootFrameworkCatalogTask() {
        nativeRuntimePackage.convention("one.xis.boot.nativeimage");
        generatedClassName.convention("XisGeneratedBootFrameworkComponents");
    }

    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public ConfigurableFileCollection getRegistrySourceRoots() {
        return registrySourceRoots;
    }

    @OutputDirectory
    public DirectoryProperty getOutputDirectory() {
        return outputDirectory;
    }

    @Input
    public Property<String> getNativeRuntimePackage() {
        return nativeRuntimePackage;
    }

    @Input
    public Property<String> getGeneratedClassName() {
        return generatedClassName;
    }

    @TaskAction
    public void generate() throws IOException {
        var outputDir = outputDirectory.get().getAsFile();
        getProject().delete(outputDir);
        var packageDir = new File(outputDir, nativeRuntimePackage.get().replace('.', '/'));
        Files.createDirectories(packageDir.toPath());
        Files.writeString(new File(packageDir, generatedClassName.get() + ".java").toPath(),
                source(readRegistryClassNames()), StandardCharsets.UTF_8);
    }

    private List<String> readRegistryClassNames() throws IOException {
        var registryFiles = registrySourceRoots.getFiles().stream()
                .filter(File::exists)
                .flatMap(root -> {
                    try {
                        return Files.walk(root.toPath())
                                .filter(path -> path.getFileName().toString().endsWith("ModuleComponents.java"))
                                .map(java.nio.file.Path::toFile);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                })
                .sorted(Comparator.comparing(File::getPath))
                .toList();
        var registryClassNames = new java.util.ArrayList<String>();
        for (var registryFile : registryFiles) {
            var source = Files.readString(registryFile.toPath(), StandardCharsets.UTF_8);
            var packageMatcher = PACKAGE_PATTERN.matcher(source);
            var classMatcher = CLASS_PATTERN.matcher(source);
            if (packageMatcher.find() && classMatcher.find()) {
                registryClassNames.add(packageMatcher.group(1) + "." + classMatcher.group(1));
            }
        }
        return registryClassNames.stream().distinct().sorted().toList();
    }

    private String source(List<String> registryClassNames) {
        return """
                package %s;

                import %s.NativeComponentRegistry;

                import java.util.Collection;
                import java.util.List;

                /**
                 * Generated by Gradle. Do not edit manually.
                 */
                public final class %s implements NativeComponentRegistry {

                    private static final List<Collection<Class<?>>> COMPONENT_GROUPS = List.of(
                %s
                    );

                    @Override
                    public Collection<Class<?>> componentClasses() {
                        return COMPONENT_GROUPS.stream()
                                .flatMap(Collection::stream)
                                .toList();
                    }
                }
                """.formatted(nativeRuntimePackage.get(), nativeRuntimePackage.get(), generatedClassName.get(),
                registryClassNames.stream()
                .map(className -> "            new " + className + "().componentClasses()")
                .collect(Collectors.joining(",\n")));
    }
}
