package one.xis.sql;

import org.h2.jdbcx.JdbcDataSource;

import javax.sql.DataSource;
import java.sql.SQLException;

public class H2SqlSystemTest extends SqlSystemTestSupport {
    private final JdbcDataSource dataSource = newDataSource();

    @Override
    DataSource dataSource() {
        return dataSource;
    }

    @Override
    void createSchema() throws SQLException {
        try (var connection = dataSource.getConnection();
             var statement = connection.createStatement()) {
            statement.execute("drop alias if exists ADD_FIVE");
            statement.execute("drop alias if exists DOUBLE_VALUE");
            statement.execute("drop table if exists date_rows");
            statement.execute("drop table if exists generated_memberships");
            statement.execute("drop table if exists generated_people");
            statement.execute("drop table if exists people");
            statement.execute("create table people (id bigint primary key, first_name varchar(100) not null, notes clob not null)");
            statement.execute("create table generated_people (id bigint generated by default as identity primary key, first_name varchar(100) not null)");
            statement.execute("""
                    create table generated_memberships (
                        tenant_id varchar(100) not null,
                        id bigint generated by default as identity,
                        label varchar(100) not null,
                        primary key (tenant_id, id)
                    )
                    """);
            statement.execute("""
                    create table date_rows (
                        id bigint primary key,
                        local_date date not null,
                        local_time time not null,
                        local_date_time timestamp not null,
                        instant_value timestamp not null,
                        util_date timestamp not null,
                        sql_date date not null,
                        sql_time time not null,
                        sql_timestamp timestamp not null
                    )
                    """);
            statement.execute("insert into people (id, first_name, notes) values (1, 'Ada', 'First note from clob'), (2, 'Grace', 'Second note')");
            statement.execute("create alias DOUBLE_VALUE for \"" + H2SqlSystemTest.class.getName() + ".doubleValue\"");
            statement.execute("create alias ADD_FIVE for \"" + H2SqlSystemTest.class.getName() + ".addFive\"");
        }
        insertDateRows();
    }

    @Override
    boolean supportsStoredProcedureOutParameters() {
        return false;
    }

    public static int doubleValue(int value) {
        return value * 2;
    }

    public static void addFive(int value, int[] result) {
        result[0] = value + 5;
    }

    private static JdbcDataSource newDataSource() {
        var dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:sql-system-test;DB_CLOSE_DELAY=-1");
        return dataSource;
    }
}
