package one.xis.ddl;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import java.sql.SQLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DDLTest {

    @Test
    void rendersCreateTableWithConstraintsAndRawSql() {
        DDL ddl = new DDL();
        Table tenants = ddl.createTableIfNotExists("tenants");
        Column tenantId = tenants.addColumn("id").bigint();
        tenants.addColumn("name").varchar(100).notNull();
        PrimaryKey tenantPk = tenants.setPrimaryKey(tenantId);

        Table users = ddl.createTableIfNotExists("app_users");
        Column userId = users.addColumn("id").bigint().generatedIdentity();
        Column userTenantId = users.addColumn("tenant_id").bigint().notNull();
        Column email = users.addColumn("email").varchar(200).notNull();
        users.setPrimaryKey(userId);
        users.addUniqueConstraint(userTenantId, email);
        users.addIndex(email);
        users.addForeignKey(tenantPk, userTenantId);
        ddl.sql("insert into tenants (id, name) values (1, 'Default')");

        assertEquals(List.of(
                "create table if not exists tenants (id bigint not null, name varchar(100) not null, constraint pk_tenants_id primary key (id))",
                "create table if not exists app_users (id bigint generated by default as identity not null, tenant_id bigint not null, email varchar(200) not null, constraint pk_app_users_id primary key (id), constraint uq_app_users_tenant_id_email unique (tenant_id, email), constraint fk_tenants_app_users_tenant_id foreign key (tenant_id) references tenants (id))",
                "create index if not exists ix_app_users_email on app_users (email)",
                "insert into tenants (id, name) values (1, 'Default')"
        ), ddl.statements(SqlDialect.POSTGRESQL));
    }

    @Test
    void rendersMariaDbIdentity() {
        DDL ddl = new DDL();
        Table table = ddl.createTableIfNotExists("items");
        Column id = table.addColumn("id").bigint().generatedIdentity();
        table.setPrimaryKey(id);

        assertEquals(List.of("create table if not exists items (id bigint auto_increment not null, constraint pk_items_id primary key (id))"),
                ddl.statements(SqlDialect.MARIADB));
    }

    @Test
    void rendersFluentColumnTypes() {
        DDL ddl = new DDL();
        Table table = ddl.createTableIfNotExists("items");
        table.addColumn("id").bigint().primaryKey()
                .addColumn("amount").decimal(12, 2).notNull()
                .addColumn("score").integer()
                .addColumn("description").text()
                .addColumn("active").bool()
                .addColumn("created_date").date()
                .addColumn("created_time").time()
                .addColumn("created_at").timestamp()
                .addColumn("raw_amount").decimal();

        assertEquals(List.of(
                "create table if not exists items (id bigint not null, amount decimal(12, 2) not null, score integer, description text, active boolean, created_date date, created_time time, created_at timestamp, raw_amount decimal, constraint pk_items_id primary key (id))"
        ), ddl.statements(SqlDialect.POSTGRESQL));
    }

    @Test
    void rendersFluentColumnConstraints() {
        DDL ddl = new DDL();
        Table table = ddl.createTableIfNotExists("items");
        table.addColumn("id").bigint().primaryKey()
                .addColumn("code").varchar(50).unique()
                .addColumn("name").varchar(100).index();

        assertEquals(List.of(
                "create table if not exists items (id bigint not null, code varchar(50), name varchar(100), constraint pk_items_id primary key (id), constraint uq_items_code unique (code))",
                "create index if not exists ix_items_name on items (name)"
        ), ddl.statements(SqlDialect.POSTGRESQL));
    }

    @Test
    void rendersSingleColumnForeignKeyShortcut() {
        DDL ddl = new DDL();
        Table userTable = ddl.createTableIfNotExists("app_users");
        userTable.addColumn("id").bigint().primaryKey()
                .addColumn("email").varchar(100).unique();
        Table sessionTable = ddl.createTableIfNotExists("sessions");
        sessionTable.addColumn("id").bigint().primaryKey()
                .addColumn("user_id").bigint().foreignKey(userTable.getColumn("id"));

        assertEquals(List.of(
                "create table if not exists app_users (id bigint not null, email varchar(100), constraint pk_app_users_id primary key (id), constraint uq_app_users_email unique (email))",
                "create table if not exists sessions (id bigint not null, user_id bigint, constraint pk_sessions_id primary key (id), constraint fk_app_users_sessions_user_id foreign key (user_id) references app_users (id))"
        ), ddl.statements(SqlDialect.POSTGRESQL));
    }

    @Test
    void rejectsMissingColumnLookup() {
        DDL ddl = new DDL();
        Table table = ddl.createTableIfNotExists("items");
        table.addColumn("id").bigint().primaryKey();

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> table.getColumn("missing_id"));

        assertTrue(exception.getMessage().contains("has no column missing_id"));
    }

    @Test
    void rejectsForeignKeyShortcutWhenReferencedColumnIsNotSinglePrimaryKey() {
        DDL ddl = new DDL();
        Table userTable = ddl.createTableIfNotExists("app_users");
        userTable.addColumn("id").bigint().primaryKey()
                .addColumn("email").varchar(100);
        Table sessionTable = ddl.createTableIfNotExists("sessions");
        Column userId = sessionTable.addColumn("user_id").bigint();

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> userId.foreignKey(userTable.getColumn("email")));

        assertTrue(exception.getMessage().contains("is not the single-column primary key"));
    }

    @Test
    void executesAgainstH2() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ddl-test;DB_CLOSE_DELAY=-1");

        DDL ddl = new DDL(dataSource);
        ddl.dropTableIfExists("app_users");
        ddl.dropTableIfExists("tenants");
        Table tenants = ddl.createTableIfNotExists("tenants");
        Column tenantId = tenants.addColumn("id").bigint();
        tenants.addColumn("name").varchar(100).notNull();
        PrimaryKey tenantPk = tenants.setPrimaryKey(tenantId);
        Table users = ddl.createTableIfNotExists("app_users");
        Column userId = users.addColumn("id").bigint().generatedIdentity();
        Column userTenantId = users.addColumn("tenant_id").bigint().notNull();
        users.addColumn("email").varchar(100).notNull();
        users.setPrimaryKey(userId);
        users.addForeignKey(tenantPk, userTenantId);
        ddl.sql("insert into tenants (id, name) values (1, 'Default')");
        ddl.sql("insert into app_users (tenant_id, email) values (1, 'ada@example.test')");

        ddl.execute();

        try (var connection = dataSource.getConnection();
             var statement = connection.createStatement();
             var resultSet = statement.executeQuery("select count(*) from app_users")) {
            assertTrue(resultSet.next());
            assertEquals(1, resultSet.getInt(1));
        }
    }

    @Test
    void canRunCreateTableIfNotExistsTwice() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ddl-idempotent-test;DB_CLOSE_DELAY=-1");

        DDL firstRun = new DDL(dataSource);
        Table firstTable = firstRun.createTableIfNotExists("items");
        Column firstId = firstTable.addColumn("id").bigint();
        firstTable.addColumn("name").varchar(100).notNull();
        firstTable.setPrimaryKey(firstId);
        firstRun.execute();

        DDL secondRun = new DDL(dataSource);
        Table secondTable = secondRun.createTableIfNotExists("items");
        Column secondId = secondTable.addColumn("id").bigint();
        secondTable.addColumn("name").varchar(100).notNull();
        secondTable.setPrimaryKey(secondId);

        secondRun.execute();
    }

    @Test
    void rejectsDuplicateTableInSameBuilder() {
        DDL ddl = new DDL();
        ddl.createTableIfNotExists("items");

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> ddl.createTableIfNotExists("items"));

        assertTrue(exception.getMessage().contains("Duplicate table"));
    }

    @Test
    void rejectsSelfReferencingForeignKey() {
        DDL ddl = new DDL();
        Table table = ddl.createTableIfNotExists("items");
        Column id = table.addColumn("id").bigint();
        PrimaryKey pk = table.setPrimaryKey(id);

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> table.addForeignKey(pk, id));

        assertTrue(exception.getMessage().contains("must not reference the same table"));
    }

    @Test
    void rejectsIncompatibleForeignKeyTypes() {
        DDL ddl = new DDL();
        Table parent = ddl.createTableIfNotExists("parents");
        Column parentId = parent.addColumn("id").bigint();
        PrimaryKey parentPk = parent.setPrimaryKey(parentId);
        Table child = ddl.createTableIfNotExists("children");
        Column childParentId = child.addColumn("parent_id").varchar(100);

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> child.addForeignKey(parentPk, childParentId));

        assertTrue(exception.getMessage().contains("is not compatible"));
    }

    @Test
    void rejectsForeignKeyColumnFromAnotherTable() {
        DDL ddl = new DDL();
        Table parent = ddl.createTableIfNotExists("parents");
        Column parentId = parent.addColumn("id").bigint();
        PrimaryKey parentPk = parent.setPrimaryKey(parentId);
        Table child = ddl.createTableIfNotExists("children");
        Table other = ddl.createTableIfNotExists("others");
        Column otherParentId = other.addColumn("parent_id").bigint();

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> child.addForeignKey(parentPk, otherParentId));

        assertTrue(exception.getMessage().contains("does not belong"));
    }

    @Test
    void rejectsMissingColumnTypeWhenRendering() {
        DDL ddl = new DDL();
        Table table = ddl.createTableIfNotExists("items");
        table.addColumn("id");

        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> ddl.statements(SqlDialect.H2));

        assertTrue(exception.getMessage().contains("has no type"));
    }

    @Test
    void quotesReservedIdentifiersForPostgresAndMariaDb() {
        DDL ddl = new DDL();
        ddl.dropTableIfExists("user");
        Table table = ddl.createTableIfNotExists("user");
        table.addColumn("id").bigint().primaryKey()
                .addColumn("order").integer();

        assertEquals(List.of(
                "drop table if exists \"user\"",
                "create table if not exists \"user\" (id bigint not null, \"order\" integer, constraint pk_user_id primary key (id))"
        ), ddl.statements(SqlDialect.POSTGRESQL));

        assertEquals(List.of(
                "drop table if exists `user`",
                "create table if not exists `user` (id bigint not null, `order` int, constraint pk_user_id primary key (id))"
        ), ddl.statements(SqlDialect.MARIADB));
    }

    @Test
    void executesReservedIdentifierQuotingAgainstH2() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ddl-reserved-identifiers-test;DB_CLOSE_DELAY=-1");

        DDL ddl = new DDL(dataSource);
        ddl.dropTableIfExists("user");
        Table table = ddl.createTableIfNotExists("user");
        table.addColumn("id").bigint().primaryKey()
                .addColumn("order").integer();

        ddl.execute();

        try (var connection = dataSource.getConnection();
             var statement = connection.createStatement()) {
            assertEquals(1, statement.executeUpdate("insert into \"user\" (id, \"order\") values (1, 7)"));
        }
    }
}
